// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuQDUK1ovnluYD5Q97vMj6f1IitaTEMY8',
    appId: '1:68467183477:web:092f77dcdf5edb01ff0d3c',
    messagingSenderId: '68467183477',
    projectId: 'mine-flu-project',
    authDomain: 'mine-flu-project.firebaseapp.com',
    storageBucket: 'mine-flu-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEQdji4z01AyGXOSjucEh9GhPWGqzoNKk',
    appId: '1:68467183477:android:adfe0ab39a08f434ff0d3c',
    messagingSenderId: '68467183477',
    projectId: 'mine-flu-project',
    storageBucket: 'mine-flu-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-HcDENpby2xza0XgADEZPuThx7oTK8MI',
    appId: '1:68467183477:ios:adc4f95d8fad0e07ff0d3c',
    messagingSenderId: '68467183477',
    projectId: 'mine-flu-project',
    storageBucket: 'mine-flu-project.appspot.com',
    iosClientId: '68467183477-od4v74ofpqoic5apr5eudqn5meinbch4.apps.googleusercontent.com',
    iosBundleId: 'com.mystuff.mynotes',
  );
}
